[package]
name = 'chall5_solution'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies]
move-lock = {local = '../ctfmovement-5/'}

[addresses]
ctfmovement = '_'
chall5 = '_'
